# Generated by Django 3.1.1 on 2020-10-01 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='duration',
            field=models.CharField(choices=[('1 month', '1 month'), ('3 months', '3 months'), ('6 months', '6 months'), ('Year', 'Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('somewhat', 'somewhat')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='new_property',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='parking_space',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Office', 'Office'), ('Business', 'Business'), ('Other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='storey',
            field=models.CharField(choices=[('Bungalow', 'Bungalow'), ('Duplex', 'Duplex'), ('One Storeys', 'One Storeys'), ('Two Storeys', 'Two Storeys'), ('Three Storeys', 'Three Storeys'), ('Four Storeys', 'Four Storeys'), ('Five Storeys', 'Five Storeys')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='neighborhoods/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, default=1, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='property.category')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.ForeignKey(blank=True, default='1', max_length=300, on_delete=django.db.models.deletion.CASCADE, to='property.neighborhood'),
        ),
    ]
