# Generated by Django 3.1.1 on 2020-10-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_remove_property_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='category',
        ),
    ]
