# Generated by Django 3.1.1 on 2020-10-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_neighborhood_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='category',
            field=models.ForeignKey(blank=True, default=1, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='property.category'),
        ),
    ]
