# Generated by Django 3.1.1 on 2020-10-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20201004_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_category',
            field=models.CharField(choices=[('1000-5000', '1000-5000'), ('5000-10000', '5000-10000'), ('10000-15000', '10000-15000'), ('15000-20000', '15000-20000'), ('20000-30000', '20000-30000'), ('30000-50000', '30000-50000'), ('50000-75000', '50000-75000'), ('75000-100000', '75000-100000'), ('100000-125000', '100000-125000'), ('125000-150000', '125000-150000'), ('150000-200000', '150000-200000'), ('200000-1000000', '200000-1000000')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=50),
        ),
    ]
