# Generated by Django 3.1.1 on 2020-10-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20201007_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pricecat',
            field=models.CharField(choices=[('1000 --> 5000 QAR', '1000 --> 5000 QAR'), ('5000 --> 10000 QAR', '5000 --> 10000 QAR'), ('10000 --> 15000 QAR', '10000 --> 15000 QAR'), ('15000 --> 20000 QAR', '15000 --> 20000 QAR'), ('20000 --> 30000 QAR', '20000 --> 30000 QAR'), ('30000 --> 50000 QAR', '30000 --> 50000 QAR'), ('50000 --> 75000 QAR', '50000 --> 75000 QAR'), ('75000 --> 100000 QAR', '75000 --> 100000 QAR'), ('100000 --> 125000 QAR', '100000 --> 125000 QAR'), ('125000 --> 150000 QAR', '125000 --> 150000 QAR'), ('150000 --> 200000 QAR', '150000 --> 200000 QAR'), ('200000 --> 1000000 QAR', '200000 --> 1000000 QAR')], max_length=50),
        ),
    ]
